#!/usr/bin/python3
# -*- coding: UTF-8 -*-

'''Run self tests.'''

# (c) 2008 Alberto Milone <albertomilone@alice.it>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

import unittest, os.path, sys, logging, os

def main():
    # run all tests in our directory, or just the ones given as arguments
    args = sys.argv[1:]
    if args:
        suite = unittest.TestLoader().loadTestsFromNames(args)
    else:
        suite = unittest.TestLoader().loadTestsFromNames(
            [t[:-3] for t in os.listdir(os.path.dirname(__file__))
            if t.endswith('.py') and t not in ['__init__.py', 'patchos.py'] and not
            (t == 'gpu-manager.py' and '86' not in os.uname()[4])])
    res = unittest.TextTestRunner(verbosity=2).run(suite)
    return len(res.errors) + len(res.failures)

if __name__ == '__main__':
    # run ourselves through umockdev-wrapper
    if 'umockdev' not in os.environ.get('LD_PRELOAD', ''):
        os.execvp('umockdev-wrapper', ['umockdev-wrapper'] + sys.argv)

    sys.exit(main())
